export * from './Avatar';
export * from './Button';
export * from './Carousel';
export * from './Pesquisa';
export * from './Jumbotron';
export * from './Logo';
export * from './Menu';
export * from './MovieCard';
export * from './NavBar';
